### PR TITLE
Refspropswhatsits

### PR DESCRIPTION
**Pull request by zautumnz**

### CODE REVIEW

**Comment by zautumnz** [comment]
mergggging

**Comment by romines** [comment]
@zacanger you have got to get better at commit messages! Or squash non meaningful commits!

**Comment by zautumnz** [comment]
@romines you're right. i need to get rid of the following from my configs...
`alias gg='git add -A && git commit -am "foo" && git push'`

**Comment by romines** [comment]
Haha that explains some of it at least..

**Comment by romines** [comment]
Remember when that guy came and showed us how to use the comments on github? Thank goodness he did...

**Comment by zautumnz** [comment]
fer surrre.
i actually have a gitmessage, and every real commit opens it up with fields to fill. vim yells at me when i don't have enough detail. but this is more fun than good commit messages.

**Pull request merged**
